// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJzfrqCLvwvjFE4OYnlv6t6dMo9d6NRCE',
    appId: '1:755910340909:web:e35a5e490dbc80f7dba3a4',
    messagingSenderId: '755910340909',
    projectId: 'footballappgp',
    authDomain: 'footballappgp.firebaseapp.com',
    databaseURL: 'https://footballappgp-default-rtdb.firebaseio.com',
    storageBucket: 'footballappgp.appspot.com',
    measurementId: 'G-J6PSK79RS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3wWKKDogKceJYcICyMNr4AwGbquGty7I',
    appId: '1:755910340909:android:5b90d5f559eb8334dba3a4',
    messagingSenderId: '755910340909',
    projectId: 'footballappgp',
    databaseURL: 'https://footballappgp-default-rtdb.firebaseio.com',
    storageBucket: 'footballappgp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDtE8yMLsp2NLJ_UwWulJxs2HrCzVf2T4',
    appId: '1:755910340909:ios:e711913e615162a7dba3a4',
    messagingSenderId: '755910340909',
    projectId: 'footballappgp',
    databaseURL: 'https://footballappgp-default-rtdb.firebaseio.com',
    storageBucket: 'footballappgp.appspot.com',
    iosBundleId: 'com.example.footballApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDtE8yMLsp2NLJ_UwWulJxs2HrCzVf2T4',
    appId: '1:755910340909:ios:e711913e615162a7dba3a4',
    messagingSenderId: '755910340909',
    projectId: 'footballappgp',
    databaseURL: 'https://footballappgp-default-rtdb.firebaseio.com',
    storageBucket: 'footballappgp.appspot.com',
    iosBundleId: 'com.example.footballApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJzfrqCLvwvjFE4OYnlv6t6dMo9d6NRCE',
    appId: '1:755910340909:web:d03962189d9317b5dba3a4',
    messagingSenderId: '755910340909',
    projectId: 'footballappgp',
    authDomain: 'footballappgp.firebaseapp.com',
    databaseURL: 'https://footballappgp-default-rtdb.firebaseio.com',
    storageBucket: 'footballappgp.appspot.com',
    measurementId: 'G-QLPKZQDXCQ',
  );
}
